import Head from 'next/head'
import { Inter } from 'next/font/google'

import styles from '@/styles/Home.module.scss'
import Title from '@/components/ui/Title'
import Filters from '@/components/ui/Filters'
import Posts from '@/components/Posts'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='container'>
                <div className={styles.wrapper}>
                    <Title text='323' />
                    <Filters />
                    <Posts />
                </div>
            </div>
        </>
    )
}
