import { useState } from 'react'

import Head from 'next/head'

import styles from '@/styles/Home.module.scss'
import Title from '@/components/ui/title/Title'
import Filters from '@/components/filters/Filters'
import Posts from '@/components/posts/Posts'

export default function Home() {
    const [filters, setFilters] = useState([])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='container'>
                <div className={styles.wrapper}>
                    <Title filters={filters} />
                    <Filters filters={filters} setFilters={setFilters} />
                    <Posts filters={filters} setFilters={setFilters} />
                </div>
            </div>
        </>
    )
}
